# Generated by Django 3.2.12 on 2022-03-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220308_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
