# Generated by Django 3.1.12 on 2022-04-18 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20220418_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
