# Generated by Django 3.2.12 on 2022-04-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_views'),
        ('posts', '0003_post_views'),
    ]

    operations = [
    ]
