# Generated by Django 3.2.12 on 2022-04-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_merge_0002_post_views_0003_post_views'),
        ('posts', '0005_alter_comment_post'),
    ]

    operations = [
    ]
