# Generated by Django 3.2.12 on 2022-04-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20220415_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='a_count',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='b_count',
        ),
    ]
